###Numpy and Pandas

###Numpy and Pandas.''

<h1 style = "color:blue"><i>Numpy</i></h1>

Defaulting to user installation because normal site-packages is not writeable


In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

In [10]:
import numpy as np
arr=np.array([[1,2,3,4],[9,8,7,6],[5,6,7,8]])
print(arr)
arr

[[1 2 3 4]
 [9 8 7 6]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [5, 6, 7, 8]])

In [18]:
import numpy as np
arr=np.array([[[5,6,7,8],[1,2,3,4],[9,8,7,6]],[[5,6,7,8],[1,2,3,4],[9,8,7,6]],[[5,6,7,8],[1,2,3,4],[9,8,7,6]]])
print(arr)
print(arr.ndim)
arr*2

[[[5 6 7 8]
  [1 2 3 4]
  [9 8 7 6]]

 [[5 6 7 8]
  [1 2 3 4]
  [9 8 7 6]]

 [[5 6 7 8]
  [1 2 3 4]
  [9 8 7 6]]]
3


array([[[10, 12, 14, 16],
        [ 2,  4,  6,  8],
        [18, 16, 14, 12]],

       [[10, 12, 14, 16],
        [ 2,  4,  6,  8],
        [18, 16, 14, 12]],

       [[10, 12, 14, 16],
        [ 2,  4,  6,  8],
        [18, 16, 14, 12]]])

In [12]:
import numpy as np
arr=np.array([[1,2,3,4],[9,8,7,6],[5,6,7,8]])
arr.ndim

2

In [21]:
import numpy as np
arr=np.array([[[[5,6,7],[1,2,3],[9,8,7]],[[5,6,7],[1,2,3],[9,8,7]],[[5,7,8],[1,2,3],[9,8,7]]]])
print(arr)
print(arr.shape)
arr*2

[[[[5 6 7]
   [1 2 3]
   [9 8 7]]

  [[5 6 7]
   [1 2 3]
   [9 8 7]]

  [[5 7 8]
   [1 2 3]
   [9 8 7]]]]
(1, 3, 3, 3)


array([[[[10, 12, 14],
         [ 2,  4,  6],
         [18, 16, 14]],

        [[10, 12, 14],
         [ 2,  4,  6],
         [18, 16, 14]],

        [[10, 14, 16],
         [ 2,  4,  6],
         [18, 16, 14]]]])

In [24]:
ar = np.arange(20,50)
ar

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
arr=np.array([80,70,60,75,85])
boola=arr>60
boola

array([ True,  True, False,  True,  True])

In [27]:
print(arr[0])
print(arr[-1])
print(arr[::-1])
print(arr[0:4])


80
85
[85 75 60 70 80]
[80 70 60 75]


In [33]:
np.append(arr,7)
arr

array([80, 70, 60, 75, 85])

In [32]:
ar=np.array([80,70,60,75,85])
s= np.where(ar>60,ar+1,ar)
s

array([81, 71, 60, 76, 86])

In [51]:
import numpy as np
order_amount=np.array(list(map(int,input.split())
print(order_amount)



AttributeError: 'tuple' object has no attribute 'split'

In [4]:
import numpy as np
arr =np.arange(1,10)
arr2=arr.reshape(3,3)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.nbytes)
print(arr2.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
72
8


In [6]:
be=np.zeros((2,3),dtype=int)
print(be)

[[0 0 0]
 [0 0 0]]


In [7]:
me=np.ones((2,3),dtype=int)
print(me)

[[1 1 1]
 [1 1 1]]


In [2]:
import numpy as np
np.random.seed(0)
n=np.random.choice(np.arange(1,100))
arr1=np.random.randint(10,size=(3))
arr2=np.random.randint(10,size=(2,4))
arr3=np.random.randint(10,size=(2,4,1))
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [3]:
arr_1=np.array([1,3],[4,5])
arr_2=np.array([2])
arr_1*arr_2

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [5]:
print("sum  of values of arr1: ",np.sum(arr1))
print("max  of values of arr1: ",np.max(arr1))
print("min of values of arr1: ",np.min(arr1))

sum  of values of arr1:  8
max  of values of arr1:  5
min of values of arr1:  0


In [9]:
s1="cat"
s2="act"
if(sorted(s1)==sorted(s2)):
    print("anagram")
else:
    print("Not a anagram")

anagram
